server:
  port: 8085
spring:
  servlet:
    multipart:
      file-size-threshold: 1MB
      location: C:/temp
      max-file-size: 100MB
      max-request-size: 100MB
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://127.0.0.1:3306/at?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul&useOldAliasMetadataBehavior=true&zeroDateTimeNehavior=convertToNull
    username: sbsst
    password: sbs123414
mybatis:
  type-aliases-package: com.sbs.jhs.at.dto
custom:
  logoText: 오디션 트리